### PR TITLE
Proposal: sliders on the toolbar

### PR DESCRIPTION
**Pull request by Nico-Duduf**
Hi!

First, thanks a lot for this awesome app, finally a mind map application simple enough to be used in a useful way :)

I've added some sliders on the toolbar (where you set the text size, etc) which I think are a bit more practical than just spin boxes.

The best would be to use scrollbars instead of a spinbox+slider, which would take less room by displaying the text on top of the slider (and we could show a spinbox on click without drag to still be able to input precise values). Just like what is used in Blender.

I'll do this ASAP, these slider addition is just a temporary quick way to make these values easier to adjust.

### CODE REVIEW

**Comment by juzzlin** [comment]
Hi, I'm glad to hear that you like Heimer :) 

I tested this and kind of liked the usability improvement, but I'd still rather like to see the final implementation like you explained. In my opinion there should be only well-thought and finished stuff in the master branch. I hope you'll understand this.

**Comment by juzzlin** [comment]
Also, please notice that there's `.clang-format` config for (automatic) code formatting. If you are using Qt Creator, clang-format can be enabled out-of-the-box.

**Comment by Nico-Duduf** [comment]
No problem, I added this for me, but I completely understand you'd prefer wait for something cleaner ;)

I did not see the .clang-format, thanks!

**Comment by Nico-Duduf** [comment]
Hi again! it's been a long time but I've finally found some time to add the new sliders. I used custom widgets from another project by adding the files in the `contrib` folder, I hope it's ok

**Comment by juzzlin** [comment]
Hi,

Seems that there's a file missing:

`
src/main_window.cpp:28:10: fatal error: duqfdoublespinbox.h: No such file or directory
   28 | #include "duqfdoublespinbox.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
`

**Comment by Nico-Duduf** [comment]
?? How's that possible ? Haha sorry! I'll check asap

**Pull request closed without merging**
