### PR TITLE
logo add

### PR DESCRIPTION
**Pull request by psikoz**

### CODE REVIEW

**Comment by juzzlin** [comment]
Could you also update the PNG files under data? The application is using data/images/about.png, data/icons/heimer.ico (for Windows) and data/icons/heimer.png. Currently we need to manually generate these files from the source SVG files.

**Comment by psikoz** [comment]
- I added svg at the same size instead of png's.
- I added .ico in the same size. (in the sizes you say)

Please check it.

**Comment by juzzlin** [comment]
You cannot just delete the PNG files, because the application needs the PNG files. They should be exactly the same name. Do you know how to build the application?

If you want me to do this I can take the previous commit and replace the files.

**Comment by juzzlin** [comment]
After the graphics update you should be able to still build and run the application.

**Comment by psikoz** [comment]
Sorry, I don't know how to use github. Because, I'm new here yet. So I am very confused :/ 

Can I send you a new pr? I will just upload the required files. (favicon,png,svg) 

please tell me where to upload these required files.  Can you make the other steps?

**Comment by juzzlin** [comment]
I don't actually "use" GitHub myself at all. I use git in Linux command line and make my changes there. Then I just push the commits to GitHub. 

I don't know what tools you are using, but your files were otherwise ok, they were just in wrong directories and some of them were in wrong format (the old about.png should have been replaced with your new about.png etc). Now you just deleted the old one, but did not add the new about.png :)

But don't worry, I'll pick your work from your earlier pull request without merging it directly. No need to make another PR :)

You can also send the newest files via e-mail: juzzlin@gmail.com

I will then take the files and copy them to correct locations and make a commit of that.

**Comment by juzzlin** [comment]
Some more info: If you take a look at `data/images/images.qrc` you can see that the image files are configured in this resource file. These files need to be in the same directory and the names cannot be changed here.

**Comment by juzzlin** [comment]
If it's not too much trouble could you also draw some other icon styles, for example something like the original logo but with only three nodes maybe? :) You seem to be good at creating logos.

**Comment by psikoz** [comment]
I will send all the files that will be required to you by mail. I tried 3 nodes. How is these? 


I will send the result logos of required files after I have decided.

**Comment by juzzlin** [comment]
Those are also nice, but by three nodes I meant three "boxes" :) Could be
also without the Qt style..?

**Pull request closed without merging**
