### PR TITLE
Update and rename heimer_fi.ts to heimer_it.ts

### PR DESCRIPTION
**Pull request by albanobattistella**

### CODE REVIEW

**Comment by albanobattistella** [comment]
Hi,

thanks for your answers.
It would be better in my opinion or put  PO some of all the languages, so everyone can translate your beautiful project.
Or use transfix for online translations that are updated.
Maybe I was wrong to load it so .. I see to correct everything.

Congratulations again for your project, which we would like to use in schools.

thank you.

Albano

________________________________
Da: Jussi Lind <notifications@github.com>
Inviato: sabato 20 aprile 2019 13:47
A: juzzlin/Heimer
Cc: albanobattistella; Author
Oggetto: Re: [juzzlin/Heimer] Update and rename heimer_fi.ts to heimer_it.ts (#57)


@juzzlin requested changes on this pull request.

Could you create a new file instead of renaming and changing Finnish translations? Also the data/translations/heimer_it.qm is needed + relevant changes to data/translations/translations.qrc because this is a new translation. Please take a look at "Adding/updating translations" in CONTRIBUTING.md.

Please ask if you have any questions :)

**Comment by juzzlin** [comment]
Okay, I now had the motivation to do this myself :) There were some problems with ampersands, but I fixed those and the translations are now in the master branch. Thanks!

**Comment by albanobattistella** [comment]
Thanks!!

It Is a great software.
Thank you for your good job!
Regards,
Albano

________________________________
Da: Jussi Lind <notifications@github.com>
Inviato: domenica 16 giugno 2019 11:03:49
A: juzzlin/Heimer
Cc: albanobattistella; Author
Oggetto: Re: [juzzlin/Heimer] Update and rename heimer_fi.ts to heimer_it.ts (#57)


Okay, I now had the motivation to do this myself :) There were some problems with ampersands, but I fixed those and the translations are now in the master branch. Thanks!

**Comment by albanobattistella** [comment]
how are you?
I hope all is well.
I am following the development of heimer and will install it of defult in the next release of zorin 15 educationl scheduled for late August.
I noticed that there are no Italian translations for the choice of color (grid)
also missing when you save the map where it asks you to exit without saving, cancel, or save.
I wouldn't want it to be my problem since I had a previous version installed
I remain at your disposal for further help you need.
best regards,

albano

**Pull request closed without merging**
